version: '3.8'

services:
  php:
    #command: 'composer install --no-interaction --prefer-dist --no-progress --ansi'
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/app'
      - '.docker/php/php.ini:/usr/local/etc/php/php.ini'
    ports:
      - "8000:8000" # swoole
    expose:
      - "9000" # yasd
    environment:
      - APP_RUNTIME=Runtime\Swoole\Runtime
      - PHP_IDE_CONFIG=serverName=swoole
